Code/pgms/file/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'file'

urlpatterns = [
    url(r'^$', views.file, name='file'),
    url(r'^uploads/$', views.upload, name='upload'),
    url(r'^delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete'),
]


Code/pgms/pgms/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
import sys
sys.path.append('../')
from Profile import views

urlpatterns = [
	url(r'^admin/logout/$', views.logout_user, name='logout_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Profile.urls')),
    url(r'^', include('Appointment.urls')),
    url(r'^', include('Transaction.urls')),
    url(r'^', include('Application.urls')),
    url(r'^subject/', include('subject.urls')),
    url(r'^file/', include('file.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Code/pgms/subject/urls.py
from django.conf.urls import url
from . import views
from django.core.urlresolvers import reverse

app_name = 'subject'

urlpatterns = [
    #url(r'^$',views.home, name='home'),
    url(r'^subject/$',views.subject, name='subject'),
    url(r'^subject/enroll/$', views.enroll_subject, name='enroll'),
    url(r'^subject/delete/(?P<enroll_id>[0-9]+)/$', views.delete, name='delete'),
    ]

Code/pgms/subject/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Subject(models.Model):
    name = models.CharField(max_length=250, blank=False)
    credit_hour = models.IntegerField(blank = False)
    fee = models.DecimalField(max_digits=7,decimal_places=2,blank = False)
    def __str__(self):
        return self.name



class Enroll(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)
    gpa = models.DecimalField(max_digits=3, decimal_places=2, blank=True, default="0.00")

    def __str__(self):
        return self.student.username + ' - ' + self.subject.name

Code/pgms/subject/forms.py
from django import forms

from .models import Subject,Enroll


class EnrollForm(forms.ModelForm):
    class Meta:
        model = Enroll
        fields = ('student','subject')
        widgets = {'student': forms.HiddenInput()}


Code/pgms/subject/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.core.urlresolvers import reverse
from django.http import Http404
from Profile.models import Profile
from django.contrib.auth import logout
from .models import Subject, Enroll
from .forms import EnrollForm
from Appointment.models import Appointment
from Application.models import Application
from django.db.models import Q
from Profile.forms import ProgressForm

# Create your views here.

def subject(request):
    profile = Profile.objects.get(pk=request.user.id)

    # Search bar stuff
    all_profiles = Profile.objects.all().filter(
        Q(user_type="Supervisor") | Q(user_type="Student")
    ).distinct()
    query = request.GET.get("q")
    if query:
        all_profiles = all_profiles.filter(
            Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                user__first_name__contains=query) | Q(user__last_name__contains=query)
        ).distinct()
        return render(request, 'Profile/search.html',
                      {'all_profiles': all_profiles, 'profile': profile, 'application': application, })

    # Notification bar stuff
    if profile.user_type == 'Supervisor':
        approved_app = Appointment.objects.filter(lecID=profile.user)
        form = ProgressForm(request.POST or None)
        if request.POST:
            if form.is_valid():
                progress = form.cleaned_data.get("br_progress")
                target_profile.br_progress = progress
                target_profile.save()
        if request.POST.get("reject"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Reject"
            app.save()
        elif request.POST.get("accept"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Approve"
            app.save()

            return render(request, 'subject/Subject.html', {'subjects': subjects, 'profile': profile, })
    elif profile.user_type == 'Student':
        try:
            application = Application.objects.get(app_student=request.user.id)
        except Application.DoesNotExist:
            application = None
            approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))

    if profile.user_type == 'Admin':
        logout(request)
        return render(request, 'Profile/login.html', {'error_message': 'You are NOT allowed to enter this page.'})
    else:
        subjects = Enroll.objects.filter(student=request.user)
        return render(request, 'subject/Subject.html',{'subjects': subjects, 'profile': profile, })

def delete(request, enroll_id):
    profile = Profile.objects.get(pk=request.user.id)

    # Search bar stuff
    all_profiles = Profile.objects.all().filter(
        Q(user_type="Supervisor") | Q(user_type="Student")
    ).distinct()
    query = request.GET.get("q")
    if query:
        all_profiles = all_profiles.filter(
            Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                user__first_name__contains=query) | Q(user__last_name__contains=query)
        ).distinct()
        return render(request, 'Profile/search.html',
                      {'all_profiles': all_profiles, 'profile': profile, 'application': application, })

    # Notification bar stuff
    if profile.user_type == 'Supervisor':
        approved_app = Appointment.objects.filter(lecID=profile.user)
        form = ProgressForm(request.POST or None)
        if request.POST:
            if form.is_valid():
                progress = form.cleaned_data.get("br_progress")
                target_profile.br_progress = progress
                target_profile.save()
        if request.POST.get("reject"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Reject"
            app.save()
        elif request.POST.get("accept"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Approve"
            app.save()

        return render(request, 'Profile/profile_supervisor.html',
                      {'form': form, 'profile': profile, 'target_profile': target_profile,
                       'approved_app': approved_app, })
    elif profile.user_type == 'Student':
        try:
            application = Application.objects.get(app_student=request.user.id)
        except Application.DoesNotExist:
            application = None
            approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))

    if profile.user_type == 'Admin':
        logout(request)
        return render(request, 'Profile/login.html', {'error_message': 'You are NOT allowed to enter this page.'})

    else:
        enroll = Enroll.objects.get(pk=enroll_id)
        fee = enroll.subject.fee
        profile.user_feesOwed -= fee
        profile.save()
        enroll.delete()
        return redirect('subject:subject')

def enroll_subject(request):
    profile = Profile.objects.get(pk=request.user.id)

    # Search bar stuff
    all_profiles = Profile.objects.all().filter(
        Q(user_type="Supervisor") | Q(user_type="Student")
    ).distinct()
    query = request.GET.get("q")
    if query:
        all_profiles = all_profiles.filter(
            Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                user__first_name__contains=query) | Q(user__last_name__contains=query)
        ).distinct()
        return render(request, 'Profile/search.html',
                      {'all_profiles': all_profiles, 'profile': profile, 'application': application, })

    # Notification bar stuff
    if profile.user_type == 'Supervisor':
        approved_app = Appointment.objects.filter(lecID=profile.user)
        form = ProgressForm(request.POST or None)
        if request.POST:
            if form.is_valid():
                progress = form.cleaned_data.get("br_progress")
                target_profile.br_progress = progress
                target_profile.save()
        if request.POST.get("reject"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Reject"
            app.save()
        elif request.POST.get("accept"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Approve"
            app.save()

        return render(request, 'Profile/profile_supervisor.html',
                      {'form': form, 'profile': profile, 'target_profile': target_profile,
                       'approved_app': approved_app, })
    elif profile.user_type == 'Student':
        try:
            application = Application.objects.get(app_student=request.user.id)
        except Application.DoesNotExist:
            application = None
            approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))

    if profile.user_type == 'Admin':
        logout(request)
        return render(request, 'Profile/login.html', {'error_message': 'You are NOT allowed to enter this page.'})
    else:
        student = request.user
        form = EnrollForm(request.POST or None, initial={'student': student})
        form.fields["subject"].queryset = Subject.objects.exclude(enroll__student=student)
        if form.is_valid():
            enroll = form.save(commit=False)
            enroll.student = request.user
            fee = enroll.subject.fee
            profile.user_feesOwed += fee
            enroll.save()
            profile.save()
            return redirect('subject:subject')
        return render(request, 'subject/enroll.html', {'form': form, 'profile':profile})

Code/pgms/subject/templates/subject/Subject.html
<!DOCTYPE html>
<html lang="en">
{% extends 'Profile/side_bar.html' %}
{% block content %}
{% load staticfiles %}
<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="form-profile">
			  <h2>Enrolled Subjects</h2>

				  <div class="table-responsive">
				  <table class="table">
					<thead>
					  <tr>
						<th>Subject name</th>
						  <th>Credit Hour</th>
					  <th>Fee</th>
						<th></th>
					  </tr>
					</thead>
					<tbody>
					  {% for obj in subjects %}
						<tr>
						<td>
						<a> {{ obj.subject.name }}</a>
					  </td>
						<td>
						<a> {{ obj.subject.credit_hour }}</a>
					  </td>
					  <td>
					  <a> RM {{ obj.subject.fee }}</a>
					  </td>
					  <td>
						<form action="{% url 'subject:delete' obj.id  %}" method="post" style="display: inline;">
						  {% csrf_token %}
						  <input type="hidden" name="enroll_id" value="{{ enroll.id }}" />
						  <button type="submit" class="btn btn-danger btn-xs">
							<span class="glyphicon glyphicon-remove"></span> Delete
						  </button>
						</form>
					  </td>
					</tr>
					{% endfor %}
					</tbody>
				  </table>

				<a href="{% url 'subject:enroll' %}" class="btn btn-default">Enroll subject</a>
{% endblock %}



</html>

Code/pgms/subject/templates/subject/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Subject</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

Code/pgms/subject/templates/subject/enroll.html
<!DOCTYPE html>
<html lang="en">
{% extends 'Profile/side_bar.html' %}
{% block content %}
{% load staticfiles %}
<div class="col-md-8 col-sm-8 col-xs-12">
					<div class="form-profile table-responsive">
							<h1>Choose your subject</h1>
                            <br />
                            <br />
                        <body>
                          <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                              <p><a href="{% url 'subject:subject' %}" class = "btn btn-default pull-right">Return</a></p>
                            <button type="submit" class = "btn btn-primary pull-right">Enroll</button>
                          </form>

                          </body>




{% endblock %}
</html>

Code/pgms/subject/templates/subject/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

Code/pgms/subject/templates/subject/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manage Your Subject</title>
</head>
<body>

<p>Your Subjects:</p>
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>GPA</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    {% for obj in subjects %}
    <tr>
        <td>
        <a> {{ obj.subject.name }}</a>
      </td>
      <td>
      {% if obj.gpa == 0.00 %}
        <a>-</a>
      {% else %}
        <a>{{ obj.gpa }}</a>
      </td>
      {%endif%}
      <td>
        <form action="{% url 'subject:delete' obj.id  %}" method="post" style="display: inline;">
          {% csrf_token %}
          <input type="hidden" name="enroll_id" value="{{ enroll.id }}" />
          <button type="submit" class="btn btn-danger btn-xs">
            <span class="glyphicon glyphicon-remove"></span> Delete
          </button>
        </form>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

  <ul>
    <li>
      <a href="{% url 'subject:enroll'  %}">Add a Subject</a>
    </li>
  </ul>

</body>
</html>