Code/pgms/Profile/urls.py
from django.conf.urls import url
from . import views

app_name = 'Profile'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login_user, name='login_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
    url(r'^search/$', views.search, name='search'),
]

Code/pgms/file/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'file'

urlpatterns = [
    url(r'^$', views.file, name='file'),
    url(r'^uploads/$', views.upload, name='upload'),
    url(r'^delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete'),
]


Code/pgms/pgms/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
import sys
sys.path.append('../')
from Profile import views

urlpatterns = [
	url(r'^admin/logout/$', views.logout_user, name='logout_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Profile.urls')),
    url(r'^', include('Appointment.urls')),
    url(r'^', include('Transaction.urls')),
    url(r'^', include('Application.urls')),
    url(r'^subject/', include('subject.urls')),
    url(r'^file/', include('file.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Code/pgms/file/models.py
from django.db import models
from django.conf import settings
import datetime
from Profile.models import BaseProfile
# Create your models here.

class File(models.Model):
    file_title = models.CharField(max_length=250, blank=False)
    file_upload = models.FileField(upload_to='File/')
    uploaded_at = models.DateTimeField(auto_now_add=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='file', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.file_title + ' ( ' + self.owner.username + ')'



Code/pgms/file/forms.py
from django import forms

from file.models import File


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file_title', 'file_upload' )

Code/pgms/file/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from Appointment.models import Appointment
from django.db.models import Q
from Profile.models import Profile,Supervise
from Application.models import Application
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import logout
from .models import File
from .forms import FileForm
from Profile.forms import ProgressForm

# Create your views here.

def file(request):
    profile = Profile.objects.get(pk=request.user.id)

    # Search bar stuff
    all_profiles = Profile.objects.all().filter(
        Q(user_type="Supervisor") | Q(user_type="Student")
    ).distinct()
    query = request.GET.get("q")
    if query:
        all_profiles = all_profiles.filter(
            Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                user__first_name__contains=query) | Q(user__last_name__contains=query)
        ).distinct()
        return render(request, 'Profile/search.html',
                      {'all_profiles': all_profiles, 'profile': profile, 'application': application, })

    # Notification bar stuff
    if profile.user_type == 'Supervisor':
        approved_app = Appointment.objects.filter(lecID=profile.user)
        form = ProgressForm(request.POST or None)
        if request.POST:
            if form.is_valid():
                progress = form.cleaned_data.get("br_progress")
                target_profile.br_progress = progress
                target_profile.save()
        if request.POST.get("reject"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Reject"
            app.save()
        elif request.POST.get("accept"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Approve"
            app.save()

            return render(request, 'file/File.html', {'my_files': my_files, 'files': files, 'profile': profile, 'approved_app': approved_app})
    elif profile.user_type == 'Student':
        try:
            application = Application.objects.get(app_student=request.user.id)
        except Application.DoesNotExist:
            application = None
            approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))

    if profile.user_type == 'Student':
        try:
            s = Supervise.objects.get(s_student = request.user)
            s1 = s.s_supervisor
            s2 = s.s_cosupervisor
            files = File.objects.filter(Q(owner=s1) | Q(owner=s2))
        except ObjectDoesNotExist:
            files = None
        my_files = File.objects.filter(Q(owner=request.user))
        query = request.GET.get("q")
        if query:
            if files != None:
                files = files.filter(
                    Q(file_title__contains=query)
                ).distinct()
            my_files = my_files.filter(
                Q(file_title__contains=query)
            ).distinct()
            return render(request, 'file/File.html', {'my_files':my_files,'files': files,'profile': profile,})
        else:
            return render(request, 'file/File.html', {'my_files':my_files,'files': files,'profile': profile, })

    elif profile.user_type == 'Supervisor':
        files = []
        try:
            supervise = Supervise.objects.filter(Q(s_supervisor=request.user) | Q(s_cosupervisor=request.user))
            for s in supervise:
                files += File.objects.filter(Q(owner=s.s_student))[:]
        except ObjectDoesNotExist:
            files = None
        my_files = File.objects.filter(Q(owner=request.user))
        query = request.GET.get("q")
        if query:
            files = [x for x in files if query in x.file_title]
            my_files = my_files.filter(
                Q(file_title__contains=query)
            ).distinct()

            return render(request, 'file/File.html', {'my_files':my_files,'files': files,'profile': profile,})
        else:
            return render(request, 'file/File.html', {'my_files':my_files,'files': files,'profile': profile,})
    else:
        logout(request)
        return render(request, 'Profile/login.html', {'error_message': 'You are NOT allowed to enter this page.'})


def upload(request):
    profile = Profile.objects.get(pk=request.user.id)

    # Search bar stuff
    all_profiles = Profile.objects.all().filter(
        Q(user_type="Supervisor") | Q(user_type="Student")
    ).distinct()
    query = request.GET.get("q")
    if query:
        all_profiles = all_profiles.filter(
            Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                user__first_name__contains=query) | Q(user__last_name__contains=query)
        ).distinct()
        return render(request, 'Profile/search.html',
                      {'all_profiles': all_profiles, 'profile': profile, 'application': application, })

    # Notification bar stuff
    if profile.user_type == 'Supervisor':
        approved_app = Appointment.objects.filter(lecID=profile.user)
        form = ProgressForm(request.POST or None)
        if request.POST:
            if form.is_valid():
                progress = form.cleaned_data.get("br_progress")
                target_profile.br_progress = progress
                target_profile.save()
        if request.POST.get("reject"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Reject"
            app.save()
        elif request.POST.get("accept"):
            appointmentID = request.POST.get('appointment_id', False)
            app = Appointment.objects.get(pk=appointmentID)
            app.status = "Approve"
            app.save()

            return render(request, 'file/File.html', {'my_files': my_files, 'files': files, 'profile': profile, })
    elif profile.user_type == 'Student':
        try:
            application = Application.objects.get(app_student=request.user.id)
        except Application.DoesNotExist:
            application = None
            approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))

    if profile.user_type == 'Admin':
        logout(request)
        return render(request, 'Profile/login.html', {'error_message': 'You are NOT allowed to enter this page.'})
    else:
        if request.method == 'POST':
            form = FileForm(request.POST, request.FILES)
            if form.is_valid():
                file = form.save(commit=False)
                file.owner = request.user
                file.save()
                return redirect(reverse('file:file'))

        else:
            form = FileForm()
        return render(request, 'file/upload.html', {'form': form, 'profile': profile, })


def delete_file(request, file_id):
    file = File.objects.get(pk=file_id)
    file.delete()
    return redirect('file:file')

Code/pgms/file/templates/file/File.html
<!DOCTYPE html>
<html lang="en">
{% extends 'Profile/side_bar.html' %}
{% block content %}
{% load staticfiles %}
<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="form-profile">
					<h1>File</h1>
					<div class="table-responsive">
						<form>

							<form class="navbar-form navbar-right" role="search" method="get" action="{% url 'file:file' %}">
								<div class="input-group col-md-4 col-sm-4 col-xs-12 pull-right">
									<input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.GET.q }}">
									<div class="input-group-btn">
										<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
									</div>
								</div>
							</form>

							{% if not files == None %}
								<table class="table ">
									<thead>
									  <tr>
										<th>File Name</th>
										<th>Date Uploaded</th>
										<th>By</th>
										<th></th>
										<th></th>
									  </tr>
									</thead>
									<tbody>

									{% for obj in files %}
									<tr>
									  <td>
										<p>{{ obj.file_title }}</p>
									  </td>
									  <td>
										<p> {{ obj.uploaded_at }}</p>
									  </td>
										<td>
										<a href = "{% url 'Profile:profile' obj.owner.username %}" > {{ obj.owner.username }}</a>
									  </td>
									  <td>
										<a target="_blank" href="{{ obj.file_upload.url }}">
										  <button type="button" class = "btn btn-default glyphicon glyphicon-download"></button>
										</a>
									  </td>
									  <td>
									  </td>
									</tr>
									{% endfor %}
									</tbody>
								  </table>



									<h4>Your File:</h4>
								{% endif %}
								<table class="table ">
							    <thead>
							      <tr>
							        <th>File Name</th>
							        <th>Date Uploaded</th>
								    <th></th>
									<th></th>
							      </tr>
							    </thead>
							    <tbody>
								{% for obj in my_files %}
								<tr>
								  <td>
								  <p>{{ obj.file_title }}</p>
								  </td>
								  <td>
									<p> {{ obj.uploaded_at }}</p>
								  </td>

								  <td>
									<a target="_blank" href="{{ obj.file_upload.url }}">
									  <button type="button" class = "btn btn-default glyphicon glyphicon-download"></button>
									</a>
								  </td>
								  <td>

									  <form action="{% url 'file:delete' obj.id %}" method="post" style="display: inline;">
									  {% csrf_token %}
									  <input type="hidden" name="file_id" value="{{ file.id }}" />
									  <button type="submit" class="btn btn-danger btn-xs">
										<span class="glyphicon glyphicon-remove"></span> Delete
									  </button>
									</form>
								  </td>
								</tr>
								{% endfor %}

							    </tbody>
							  </table>
								<a href="{% url 'file:upload' %}" class="btn btn-default">Upload Your File</a>



{% endblock %}
	</html>

Code/pgms/file/templates/file/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File Management</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

Code/pgms/file/templates/file/home.html
{% extends 'file/base.html' %}

{% block body %}
<body>

<form class="navbar-form navbar-left" role="search" method="get" action="{% url 'file:file' %}">
  <div class="form-group">
    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>
  <ul>
    <li>
      <a href="{% url 'file:upload' %}">Upload Your File</a>
    </li>
  </ul>

  <p>Uploaded files:</p>
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Uploaded at</th>
      <th>Uploaded by</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    {% for obj in files %}
    <tr>
      <td>
      {% if obj.file_title != ''%}
        <a>{{ obj.file_title }}</a>
      {% else %}
        <a>{{ obj.file_upload.name }}</a>
      </td>
      {%endif%}
      <td>
        <a> {{ obj.uploaded_at }}</a>
      </td>
      <td>
        <a> {{ obj.owner.username }}</a>
      </td>
      <td>
        <a target="_blank" href="{{ obj.file_upload.url }}">
          <button type="button" class="btn btn-success btn-xs">
            <span class="glyphicon glyphicon-play"></span>&nbsp;Download
          </button>
        </a>
      </td>
      <td>
        <form action="{% url 'file:delete' obj.id %}" method="post" style="display: inline;">
          {% csrf_token %}
          <input type="hidden" name="file_id" value="{{ file.id }}" />
          <button type="submit" class="btn btn-danger btn-xs">
            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
          </button>
        </form>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  </body>

{% endblock %}

Code/pgms/file/templates/file/navigation_bar.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <title>BoBoBoyz</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'Profile/css/navbar.css' %}" />
  <link rel="icon" href="Penguin.png" type="image/png"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class = "container-fluid">
		<!--logo-->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle = "collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
			</button>
			<a class = "navbar-brand active" href="Home.html">BoboBoyz</a>
				<div class="btn-nav pull-right visible-xs">
		          <a href="#" class="btn btn-notification navbar-btn dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class= "glyphicon glyphicon-bell" aria-hidden="true"></span><span class="badge badge-danger">5</span>
		          </a>
		          <ul class="dropdown-menu ">
		            <div class="notify-drop-title">
		            	<div class="row">
		                    <!--inside 1-->
		            		<div class="col-md-6 col-sm-6 col-xs-6">Notification</div>
		            		<div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title=""><i class="fa fa-dot-circle-o"></i></a></div>
		            	</div>
		            </div>
		            <!-- end notify title -->
		            <!-- notify content -->
		            <div class="drop-content">
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">James Ng</a><a href="" class="rIcon"><i class=""></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Eric Chia</a><a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Christoper Too</a><a href="" class="rIcon"><i class=""></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Alex Chan</a><a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Joker Xue</a><a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            </div>
		            <div class="notify-drop-footer text-center">
		            	<a href=""><i class="fa fa-eye"></i> See All</a>
		            </div>
		          </ul>
		    </div>
		</div>

		<!--Item-->
		<div class= "collapse navbar-collapse" id="topNavBar">
				<ul class = "nav navbar-nav visible-xs">
						<li class = "">
							<a href="Home.html">
							<span class= "glyphicon glyphicon-home"></span>
							Home</a>
						</li>
						<li class = "active">
							<a href="Profile.html">
							<span class= "glyphicon glyphicon-user"></span>
							Profile</a>
						</li>
						<li class = "">
							<a href="Subject.html">
							<span class= "glyphicon glyphicon-education"></span>
							Subject</a>
						</li>
						<li class = "">
							<a href="File.html">
							<span class= "glyphicon glyphicon-tasks"></span>
							File</a>
						</li>
						<li class="">
							<a href="AccountInquriy.html">
							<span class= "glyphicon glyphicon-stats"></span>
							Finance</a>
						</li>
				</ul>
			    <ul class="nav navbar-nav navbar-right">
		         <li class="dropdown hidden-xs">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class= "glyphicon glyphicon-bell" aria-hidden="true"></span>Notification <span class="badge badge-danger">5</span>
		          </a>
		          <ul class="dropdown-menu ">
		            <div class="notify-drop-title">
		            	<div class="row">
		                    <!--inside 1-->
		            		<div class="col-md-6 col-sm-6 col-xs-6">Notification</div>
		            		<div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title=""><i class="fa fa-dot-circle-o"></i></a></div>
		            	</div>
		            </div>
		            <!-- end notify title -->
		            <!-- notify content -->
		            <div class="drop-content">
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">James Ng</a><a href="" class="rIcon"><i class=""></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Eric Chia</a><a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Christoper Too</a><a href="" class="rIcon"><i class=""></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Alex Chan</a><a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            	<li>
		            		<div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="keke.jpg" alt=""></div></div>
		            		<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Joker Xue</a><a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
		                        <div>
		                    		<p>Date</p>
		                            <p>Time</p>
		                            <p>About</p>
		                            <button type="button" class="btn btn-danger pull-right">Reject</button>
		                            <button type="button" class="btn btn-primary pull-right">Accept</button>
		                        </div>
		            		</div>
		            	</li>
		            </div>
		            <div class="notify-drop-footer text-center">
		            	<a href=""><i class="fa fa-eye"></i> See All</a>
		            </div>
		          </ul>
		        </li>

				<li class="">
						<a href="{% url 'Profile:logout_user' %}" >
							<span class= "glyphicon glyphicon-off" aria-hidden="true"></span>Logout
						</a>
				</li>
			</ul>
			<form class="navbar-form navbar-right" role="search">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Search" name="q">
					<div class="input-group-btn">
						<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</nav>

{% block body %}
{% endblock %}

Code/pgms/file/templates/file/peek.html
{% extends 'Profile/side_bar.html' %}
{% block content %}
{% load staticfiles %}
<div class="profile-content-head">
    <h1>Personal Info</h1>
    <hr>
    <!--profile picture-->
    <div class="profile-userpic">
        <center>
            <button type="button" class="btn btn-userpic">
                {% if profile.user_photo %}
                    <img src="{{ profile.user_photo.url }}" class="img-responsive" alt="">
                {% else %}
                    <img src="{% static 'Profile/image/default.png' %}" class="img-responsive" alt="">
                {% endif %}
            </button>
        </center>
    </div>
    {% if profile.user_type == 'Student' %}
        <div class="profile-userpic">
            <table class="table table-user-information table-responsive">
                <tbody>
                    <tr>
                        <td style="text-align:right"><strong>Date of Birth:</strong></td>
                        <td>{{ application.app_birthday }}</td>
                    </tr>
                    <tr>
                        <td style="text-align:right"><strong>Gender:</strong></td>
                        <td>{{ application.app_gender }}</td>
                    </tr>
                    <tr>
                        <td style="text-align:right"><strong>Nationality:</strong></td>
                        <td>{{ application.app_nation }}</td>
                    </tr>
                    <tr>
                        <td style="text-align:right"><strong>Address:</strong></td>
                        <td>{{ application.app_address }}</td>
                    </tr>
                    <tr>
                        <td style="text-align:right"><strong>Student Type:</strong></td>
                        <td>{{ application.app_type }}</td>
                    </tr>
                        <td style="text-align:right"><strong>Programme:</strong></td>
                        <td>{{ application.app_programme }}</td>
                    </tr>
                    <tr>
                        <td style="text-align:right"><strong>Phone Number:</strong></td>
                        <td>{{ application.app_mobile_number }}</td>
                    </tr>
                        <td style="text-align:right"><strong>Email:</strong></td>
                        <td>{{ application.app_email }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    {% endif %}

</div>
{% endblock %}

Code/pgms/file/templates/file/upload.html
<!DOCTYPE html>
<html lang="en">
{% extends 'Profile/side_bar.html' %}
{% block content %}
{% load staticfiles %}
<div class="col-md-10 col-sm-8 col-xs-12">
					<div class="form-profile table-responsive">
                        <h2>Upload Your File</h2>
                        <br/>
                        <br/>
                        <body>
                          <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p><a href="{% url 'file:file' %}" class = "btn btn-default pull-right">Return</a></p>
                            <button type="submit" class = "btn btn-primary pull-right">Upload</button>
                          </form>
                        </body>


{% endblock %}
</html>