Code/pgms/Appointment/urls.py
from django.conf.urls import url
from . import views


app_name = 'Appointment'

urlpatterns = [
    url(r'^Appointment/$', views.booking, name='booking'),
]

Code/pgms/file/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'file'

urlpatterns = [
    url(r'^$', views.file, name='file'),
    url(r'^uploads/$', views.upload, name='upload'),
    url(r'^delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete'),
]


Code/pgms/pgms/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
import sys
sys.path.append('../')
from Profile import views

urlpatterns = [
	url(r'^admin/logout/$', views.logout_user, name='logout_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Profile.urls')),
    url(r'^', include('Appointment.urls')),
    url(r'^', include('Transaction.urls')),
    url(r'^', include('Application.urls')),
    url(r'^subject/', include('subject.urls')),
    url(r'^file/', include('file.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Code/pgms/Appointment/models.py
from django.db import models
from django.contrib.auth.models import User


# class Supervisor(models.Model):
#     pass
#
# class Student(models.Model):
# #    User_Status = models.CharField(max_length=7, default='studying')
# #    User_FessOwed = models.DecimalField(..., max_digits=5, decimal_places=2, default=00.00)


class Appointment(models.Model):
    Choices = (
        ('Approve', 'Approve'),
        ('Reject', 'Reject'),
        ('Pending', 'Pending'),
    )
    date = models.DateField(auto_now_add=False)
    time = models.TimeField(auto_now_add=False)
    status = models.CharField(max_length=7, choices=Choices, default='Pending')
    reason = models.CharField(max_length=200)
    lecID = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='lecID')
    stuID = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='stuID')

Code/pgms/Appointment/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Appointment


class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['date', 'time', 'reason']

Code/pgms/Appointment/views.py
from django.shortcuts import render
from Profile.models import Profile
from .models import Appointment
from Application.models import Application
from Profile.forms import ProgressForm
from django.shortcuts import render, redirect
from django.db.models import Q
from Profile.forms import ProgressForm


def booking(request):
    if not request.user.is_authenticated():
        return render(request, 'Profile/login.html')
    else:
        profile = Profile.objects.get(pk=request.user.id)

        # Search bar stuff
        all_profiles = Profile.objects.all().filter(
            Q(user_type="Supervisor") | Q(user_type="Student")
        ).distinct()
        query = request.GET.get("q")
        if query:
            all_profiles = all_profiles.filter(
                Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                    user__first_name__contains=query) | Q(user__last_name__contains=query)
            ).distinct()
            return render(request, 'Profile/search.html',
                          {'all_profiles': all_profiles, 'profile': profile, 'application': application, })

        # Notification bar stuff
        if profile.user_type == 'Supervisor':
            approved_app = Appointment.objects.filter(lecID=profile.user)
            form = ProgressForm(request.POST or None)
            if request.POST:
                if form.is_valid():
                    progress = form.cleaned_data.get("br_progress")
                    target_profile.br_progress = progress
                    target_profile.save()
            if request.POST.get("reject"):
                appointmentID = request.POST.get('appointment_id', False)
                app = Appointment.objects.get(pk=appointmentID)
                app.status = "Reject"
                app.save()
            elif request.POST.get("accept"):
                appointmentID = request.POST.get('appointment_id', False)
                app = Appointment.objects.get(pk=appointmentID)
                app.status = "Approve"
                app.save()

            return render(request, 'Profile/profile_supervisor.html',
                          {'form': form, 'profile': profile, 'approved_app': approved_app, })
        elif profile.user_type == 'Student':
            try:
                application = Application.objects.get(app_student=request.user.id)
            except Application.DoesNotExist:
                application = None
                approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))

        if profile.user_type == 'Supervisor':
            all_appointments = Appointment.objects.filter(lecID=request.user)
        else:
            all_appointments = Appointment.objects.filter(stuID=request.user)
        return render(request, 'Appointment/bookings.html', {'all_appointments': all_appointments, 'profile': profile})

Code/pgms/Appointment/templates/Appointment/bookings.html
{% extends 'Profile/side_bar.html' %}
{% block content %}
{% load staticfiles %}
<div class="profile-content-head">
	<div class="form-profile">
        <h1>My Appointment</h1>

        <div class="albums-container container-fluid">
            {% if all_appointments %}
                <div class="table-responsive">
			        <table class="table">
                        <tr>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Reason</th>
                            {% if profile.user_type == 'Supervisor' %}
                                <th>Stu's Name</th>
                            {% else %}
                                <th>Lec's Name</th>
                            {% endif %}

                            <th>Status</th>
                        </tr>
                        {% for appointment in all_appointments %}
                            <tr>
                                <td>{{ appointment.date }}</td>
                                <td>{{ appointment.time }}</td>
                                <td>{{ appointment.reason }}</td>
                                {% if profile.user_type == 'Supervisor' %}
                                    <td>{{ appointment.stuID }}</td>
                                {% else %}
                                    <td>{{ appointment.lecID }}</td>
                                {% endif %}
                                <td>{{ appointment.status }}</td>
                            </tr>
                        {% endfor %}
                </table>
            {% endif %}
        </div>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
    </div>
</div>
{% endif %}
{% endblock %}

Code/pgms/Appointment/templates/Appointment/django admin.html

<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Add appointment | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" app-Appointment model-appointment change-form"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>
        
        
        <div id="user-tools">
            
                Welcome,
                <strong>admin</strong>.
            
            
                
                    <a href="/">View site</a> /
                
                
                    
                    
                
                
                <a href="/admin/password_change/">Change password</a> /
                
                <a href="/admin/logout/">Log out</a>
            
        </div>
        
        
        
    </div>
    <!-- END Header -->
    
<div class="breadcrumbs">
<a href="/admin/">Home</a>
&rsaquo; <a href="/admin/Appointment/">Appointment</a>
&rsaquo; <a href="/admin/Appointment/appointment/">Appointments</a>
&rsaquo; Add appointment
</div>

    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        <h1>Add appointment</h1>
        <div id="content-main">



<form enctype="multipart/form-data" action="" method="post" id="appointment_form" novalidate><input type='hidden' name='csrfmiddlewaretoken' value='xzH3vNE1lRL29DnwCfPeTXm06qnfGlvoEOPPU8bCg4XMM14r9sdEMTBBv00WMqFh' />
<div>







  <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-created_at">
            
            
                <div>
                    
                    
                        <label class="required" for="id_created_at_0">Created at:</label>
                        
                            <p class="datetime">
  Date: <input type="text" name="created_at_0" class="vDateField" size="10" required id="id_created_at_0" />

<br />
  Time: <input type="text" name="created_at_1" class="vTimeField" size="8" required id="id_created_at_1" />


</p>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-status">
            
            
                <div>
                    
                    
                        <label class="required" for="id_status">Status:</label>
                        
                            <select name="status" id="id_status">
  <option value="Approve">Approve</option>

  <option value="Reject">Reject</option>

  <option value="Pending" selected>Pending</option>

</select>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-lecID">
            
            
                <div>
                    
                    
                        <label class="required" for="id_lecID">LecID:</label>
                        
                            <div class="related-widget-wrapper">
    <select name="lecID" required id="id_lecID">
  <option value="" selected>---------</option>

  <option value="1">admin</option>

  <option value="2">idiot</option>

  <option value="3">supervisor</option>

</select>
    
        <a class="related-widget-wrapper-link change-related" id="change_id_lecID"
            data-href-template="/admin/auth/user/__fk__/change/?_to_field=id&amp;_popup=1"
            title="Change selected user"><img src="/static/admin/img/icon-changelink.svg" alt="Change"/></a><a class="related-widget-wrapper-link add-related" id="add_id_lecID"
            href="/admin/auth/user/add/?_to_field=id&amp;_popup=1"
            title="Add another user"><img src="/static/admin/img/icon-addlink.svg" alt="Add"/></a>
    
</div>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-stuID">
            
            
                <div>
                    
                    
                        <label class="required" for="id_stuID">StuID:</label>
                        
                            <div class="related-widget-wrapper">
    <select name="stuID" required id="id_stuID">
  <option value="" selected>---------</option>

  <option value="1">admin</option>

  <option value="2">idiot</option>

  <option value="3">supervisor</option>

</select>
    
        <a class="related-widget-wrapper-link change-related" id="change_id_stuID"
            data-href-template="/admin/auth/user/__fk__/change/?_to_field=id&amp;_popup=1"
            title="Change selected user"><img src="/static/admin/img/icon-changelink.svg" alt="Change"/></a><a class="related-widget-wrapper-link add-related" id="add_id_stuID"
            href="/admin/auth/user/add/?_to_field=id&amp;_popup=1"
            title="Add another user"><img src="/static/admin/img/icon-addlink.svg" alt="Add"/></a>
    
</div>
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>













<div class="submit-row">
<input type="submit" value="Save" class="default" name="_save" />


<input type="submit" value="Save and add another" name="_addanother" />
<input type="submit" value="Save and continue editing" name="_continue" />
</div>



    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"
            
                data-model-name="appointment"
            >
    </script>




<script type="text/javascript"
        id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>


</div>
</form></div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

Code/pgms/Appointment/templates/Appointment/form.html
{% extends 'Profile/side_bar.html' %}
{% block content %}
{% load staticfiles %}
<div class="profile-content-head">
	<div class="form-profile">
        <!DOCTYPE html>

        <html lang="en-us" >
        <head>
            <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
            <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
            <script type="text/javascript" src="/admin/jsi18n/"></script>
            <script type="text/javascript" src="/static/admin/js/core.js"></script>
            <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
            <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
            <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
            <script type="text/javascript" src="/static/admin/js/actions.js"></script>
            <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
            <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
            <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
            <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
            <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
        </head>
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'Appointment/form_template.html' %}
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div><!--
            <div class="form-group">
                {% csrf_token %}
                <label class="control-label col-sm-2">
                    Date :
                </label>
                <div class="col-sm-10">
                    <input type="text" name="date" class="vDateField" size="10" required id="date" />
                    <a href="#" id="calendarlink0"><span class="date-icon" title="Choose a Date"></span>
                        <span class="date-icon" title="Choose a Date"></span>
                    </a>
                </div>
            </div>
            <div class="form-group">
                {% csrf_token %}
                <label class="control-label col-sm-2">
                    <span class="text-danger small">{{ field.errors }}</span>
                    Time :
                </label>
                <div class="col-sm-10">
                    <input type="text" name="time" class="vTimeField" size="8" required id="time" />
                </div>
            </div>

            <div class="form-group">
                {% csrf_token %}
                <label class="control-label col-sm-2" for="reason">
                    Reason :
                </label>
                <div class="col-sm-10">
                    <input type="text" name="reason" size="8" required id="reason" />
                </div>
            </div>

            <div class="form-group">
                {% csrf_token %}
                <label class="control-label col-sm-2" for="lecID">
                    LecID :
                </label>
                <div class="col-sm-10">
                    <input id="username" maxlength="30" name="lecID" type="text">
                </div>
            </div>
            <div class="form-group">
                {% csrf_token %}
                <label class="control-label col-sm-2" for="stuID">
                    StuID :
                </label>
                <div class="col-sm-10">
                    <input id="username" maxlength="30" name="stuID" type="text">
                </div>
            </div>

            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>-->


            <script type="text/javascript"
                    id="django-admin-prepopulated-fields-constants"
                    src="/static/admin/js/prepopulate_init.js"
                    data-prepopulated-fields="[]">
            </script>
            <!--<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'Appointment/form_template.html' %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>-->
        </form>

        </html>
    </div>
</div>
{% endblock %}

Code/pgms/Appointment/templates/Appointment/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="date">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}