Code/pgms/Appointment/urls.py
from django.conf.urls import url
from . import views


app_name = 'Appointment'

urlpatterns = [
    url(r'^Appointment/$', views.booking, name='booking'),
]

Code/pgms/Profile/urls.py
from django.conf.urls import url
from . import views

app_name = 'Profile'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login_user, name='login_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
    url(r'^search/$', views.search, name='search'),
]

Code/pgms/Transaction/urls.py
from django.conf.urls import url
from . import views

app_name = 'Transaction'

urlpatterns = [
    url(r'^transaction/$', views.account, name='account'),
    url(r'^upload_file/$', views.upload_file, name='upload_file'),
]

Code/pgms/file/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'file'

urlpatterns = [
    url(r'^$', views.file, name='file'),
    url(r'^uploads/$', views.upload, name='upload'),
    url(r'^delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete'),
]


Code/pgms/pgms/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
import sys
sys.path.append('../')
from Profile import views

urlpatterns = [
	url(r'^admin/logout/$', views.logout_user, name='logout_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Profile.urls')),
    url(r'^', include('Appointment.urls')),
    url(r'^', include('Transaction.urls')),
    url(r'^', include('Application.urls')),
    url(r'^subject/', include('subject.urls')),
    url(r'^file/', include('file.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Code/pgms/subject/urls.py
from django.conf.urls import url
from . import views
from django.core.urlresolvers import reverse

app_name = 'subject'

urlpatterns = [
    #url(r'^$',views.home, name='home'),
    url(r'^subject/$',views.subject, name='subject'),
    url(r'^subject/enroll/$', views.enroll_subject, name='enroll'),
    url(r'^subject/delete/(?P<enroll_id>[0-9]+)/$', views.delete, name='delete'),
    ]

Code/pgms/Profile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import BaseProfile, Profile
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class ProgressForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['br_progress', ]

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class ProfileEditForm(forms.ModelForm):
    first_name = forms.CharField(required=False, label='First Name')
    last_name = forms.CharField(required=False, label='Last Name')
    # user_photo = forms.FileField(required=False, label='User Photo')

    def __init__(self, *args, **kwargs):
        super(ProfileEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        # You can dynamically adjust your layout
        self.helper.layout.append(Submit('save', 'Save'))
        self.fields['first_name'] = forms.CharField(initial=self.instance.user.first_name)
        self.fields['last_name'] = forms.CharField(initial=self.instance.user.last_name)

    class Meta:
        model = BaseProfile
        fields = ['user_photo', 'first_name', 'last_name', 'user_address']

    def save_all_fields_from_request(self, request):
        user, created = User.objects.get_or_create(id=request.user.id)
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.save()
        if 'user_photo' in request.FILES:
            self.instance.user_photo = request.FILES['user_photo']
        self.save()

class ProfileEditFormResearch(forms.ModelForm):
    first_name = forms.CharField(required=False, label='First Name')
    last_name = forms.CharField(required=False, label='Last Name')
    br_title = forms.CharField(required=False, label='Research Title')

    def __init__(self, *args, **kwargs):
        super(ProfileEditFormResearch, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        # You can dynamically adjust your layout
        self.helper.layout.append(Submit('save', 'Save'))
        self.fields['first_name'] = forms.CharField(initial=self.instance.user.first_name)
        self.fields['last_name'] = forms.CharField(initial=self.instance.user.last_name)
        self.fields['br_title'] = forms.CharField(initial=self.instance.br_title)

    class Meta:
        model = Profile
        fields = ['user_photo', 'first_name', 'last_name', 'br_title', 'user_address', ]

    def save_all_fields_from_request(self, request):
        user, created = User.objects.get_or_create(id=request.user.id)
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.save()
        self.instance.user_photo = request.FILES['user_photo']
        self.instance.br_title = request.POST['br_title']
        self.save()

Code/pgms/Profile/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.db.models import Q
from .models import Profile
from Application.models import Application
from .forms import UserForm, ProfileEditForm, ProgressForm, ProfileEditFormResearch
from Application.forms import ApplicationForm
from Appointment.forms import AppointmentForm
from Appointment.models import Appointment
from Application.models import Application

def login_user(request):
    if request.method == "POST":
        if request.POST.get("login") == "Login":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    profile = Profile.objects.get(pk=request.user.id)
                    try:
                        application = Application.objects.get(app_student=request.user)
                    except Application.DoesNotExist:
                        application = None
                    if profile.user_type == 'Admin':
                        all_applications = Application.objects.filter(app_admin=None).exclude(app_admin=request.user)
                        return render(request,'Application/index.html',{'all_applications':all_applications})
                    else:
                        return redirect('Profile:home')
                else:
                    return render(request, 'Profile/login.html', {'error_message': 'Your account has been disabled'})
            else:
                return render(request, 'Profile/login.html', {'error_message': 'Invalid login'})

        elif request.POST.get("application") == "Application":
            if request.POST:
                form = ApplicationForm(request.POST, request.FILES)
                app_name_first = request.POST['app_name_first']
                app_name_last = request.POST['app_name_last']
                app_birthday = request.POST['app_birthday']
                app_gender = request.POST['app_gender']
                app_ic = request.POST['app_ic']
                app_nation = request.POST['app_nation']
                app_address = request.POST['app_address']
                app_file_upload = request.FILES['app_file_upload']
                app_file_upload2 = request.FILES['app_file_upload2']
                app_file_upload3 = request.FILES['app_file_upload3']
                app_email = request.POST['app_email']
                app_mobile_number = request.POST['app_mobile_number']
                app_type = request.POST['app_type']
                app_programme = request.POST['app_programme']
                if form.is_valid():
                    form.save()
                    return render(request, 'Profile/login.html', {'success_message':"Application submit sucessfull!"})
    return render(request, 'Profile/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'Profile/login.html', context)

def home(request):
    if not request.user.is_authenticated():
        return render(request, 'Profile/login.html')
    else:
        profile = Profile.objects.get(pk=request.user.id)

        # Notification bar stuff
        if profile.user_type == 'Supervisor':
            approved_app = Appointment.objects.filter(lecID=profile.user)
            approved_app = approved_app.filter(status="Pending")
            form = ProgressForm(request.POST or None)
            if request.POST:
                if form.is_valid():
                    progress = form.cleaned_data.get("br_progress")
                    target_profile.br_progress = progress
                    target_profile.save()
            if request.POST.get("reject"):
                appointmentID = request.POST.get('appointment_id', False)
                app = Appointment.objects.get(pk=appointmentID)
                app.status = "Reject"
                app.save()
            elif request.POST.get("accept"):
                appointmentID = request.POST.get('appointment_id', False)
                app = Appointment.objects.get(pk=appointmentID)
                app.status = "Approve"
                app.save()

            else:
                # Search bar stuff
                all_profiles = Profile.objects.all().filter(
                    Q(user_type="Supervisor") | Q(user_type="Student")
                ).distinct()
                query = request.GET.get("q")
                if query:
                    all_profiles = all_profiles.filter(
                        Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                            user__first_name__contains=query) | Q(user__last_name__contains=query)
                    ).distinct()
                    return render(request, 'Profile/search.html',
                                  {'all_profiles': all_profiles, 'profile': profile, })

            return render(request, 'Profile/home.html',
                          {'form': form, 'profile': profile, 'approved_app': approved_app, })
        elif profile.user_type == 'Student':
            try:
                application = Application.objects.get(app_student=request.user.id)
            except Application.DoesNotExist:
                application = None
            approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Approve") | Q(status="Reject"))
            form = ProgressForm(request.POST or None)
            if request.POST:
                if form.is_valid():
                    progress = form.cleaned_data.get("br_progress")
                    target_profile.br_progress = progress
                    target_profile.save()
            if request.POST.get("reject"):
                appointmentID = request.POST.get('appointment_id', False)
                app = Appointment.objects.get(pk=appointmentID)
                app.status = "Reject"
                app.save()
            elif request.POST.get("accept"):
                appointmentID = request.POST.get('appointment_id', False)
                app = Appointment.objects.get(pk=appointmentID)
                app.status = "Approve"
                app.save()

        try:
            application = Application.objects.get(app_student=request.user)
        except Application.DoesNotExist:
            application = None

        # Search bar stuff
        all_profiles = Profile.objects.all().filter(
                Q(user_type="Supervisor") | Q(user_type="Student")
            ).distinct()
        query = request.GET.get("q")
        if query:
            all_profiles = all_profiles.filter(
                Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                    user__first_name__contains=query) | Q(user__last_name__contains=query)
            ).distinct()
            return render(request, 'Profile/search.html', {'all_profiles': all_profiles, 'profile': profile, 'application': application, 'approved_app': approved_app, })

        profile = Profile.objects.get(pk=request.user.id)
        return render(request, 'Profile/home.html', {'profile': profile, 'application': application, 'approved_app': approved_app, })

def search(request):
    if not request.user.is_authenticated():
        return render(request, 'Profile/login.html')
    else:
        return render(request, 'Profile/search.html', {'all_profiles': all_profiles, 'profile': profile, })

def profile(request, username):
    if not request.user.is_authenticated():
        return render(request, 'Profile/login.html')
    else:
        profile = Profile.objects.get(pk=request.user.id)
        target_profile = Profile.objects.get(user__username=username)
        try:
            application = Application.objects.get(app_student=request.user.id)
        except Application.DoesNotExist:
            application = None

        # Search bar stuff
        all_profiles = Profile.objects.all().filter(
            Q(user_type="Supervisor") | Q(user_type="Student")
        ).distinct()
        query = request.GET.get("q")
        if query:
            all_profiles = all_profiles.filter(
                Q(user__username__contains=query) | Q(user_type__contains=query) | Q(
                    user__first_name__contains=query) | Q(user__last_name__contains=query)
            ).distinct()
            return render(request, 'Profile/search.html',
                          {'all_profiles': all_profiles, 'profile': profile, 'application': application, })


        # Notification bar stuff
        if profile.user_type == 'Supervisor':
            approved_app = Appointment.objects.filter(lecID=profile.user)
        else:
            approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))


        if profile.user_type == 'Supervisor':
            approved_app = Appointment.objects.filter(lecID=profile.user)
            form = ProgressForm(request.POST or None)
            try:
                application = Application.objects.get(app_student=request.user.id)
            except Application.DoesNotExist:
                application = None
                approved_app = Appointment.objects.filter(Q(stuID=profile.user) | Q(status="Pending"))

            if request.POST:
                if form.is_valid():
                    progress = form.cleaned_data.get("br_progress")

Code/pgms/Profile/templates/Profile/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

Code/pgms/Profile/templates/Profile/navigation_bar.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <title>BoBoBoyz</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'Profile/css/navbar.css' %}" />
  <link rel="icon" href="Penguin.png" type="image/png"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class = "container-fluid">
		<!--logo-->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle = "collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
			</button>
			<a class = "navbar-brand active" href="{% url 'Profile:home' %}">BoBoBoyz</a>
				<div class="btn-nav pull-right visible-xs">
		          <a href="#" class="btn btn-notification navbar-btn dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class= "glyphicon glyphicon-bell" aria-hidden="true"></span><span class="badge badge-danger">{{ approved_app.count }}</span>
		          </a>
		          <!--<ul class="dropdown-menu ">-->
		            <!--<div class="notify-drop-title">-->
		            	<!--<div class="row">-->
		                    <!--&lt;!&ndash;inside 1&ndash;&gt;-->
		            		<!--<div class="col-md-6 col-sm-6 col-xs-6">Notification</div>-->
		            		<!--<div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title=""><i class="fa fa-dot-circle-o"></i></a></div>-->
		            	<!--</div>-->
		            <!--</div>-->
		            <!--&lt;!&ndash; end notify title &ndash;&gt;-->
		            <!--&lt;!&ndash; notify content &ndash;&gt;-->
		            <!--<div class="drop-content">-->
						<!--{% for appointment in approved_app %}-->
							<!--{% if profile.user_type == 'Supervisor' %}-->
								<!--{% if appointment.status == 'Pending' %}-->
									<!--<li>-->
										<!--<div class="col-md-3 col-sm-3 col-xs-3">-->
											<!--<div class="notify-img">-->
												<!--{% if appointment.stuID.profile.user_photo %}-->
													<!--<img src="{{ appointment.stuID.profile.user_photo.url }}" class="img-responsive" alt="">-->
												<!--{% else %}-->
													<!--<img src="{% static 'Profile/image/default.png' %}" class="img-responsive" alt="">-->
												<!--{% endif %}-->
											<!--</div>-->
										<!--</div>-->
										<!--<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="{% url 'Profile:profile' appointment.stuID.username %}">{{ appointment.stuID }}</a><a href="" class="rIcon"><i class=""></i></a>-->
											<!--<div>-->
												<!--<p>Date  : {{ appointment.date }}</p>-->
												<!--<p>Time  : {{ appointment.time }}</p>-->
												<!--<p>About : {{ appointment.reason }}</p>-->

													<!--<form id="appointmentForm" method="post" enctype="multipart/form-data" action="">-->
														<!--{% csrf_token %}-->
														<!--<input class="hidden" name="appointment_id" value="{{ appointment.id }}">-->
														<!--<input type="submit" class="btn btn-primary pull-right" name="accept" value="Accept"></input>-->
														<!--<input type="submit" class="btn btn-danger pull-right" name="reject" value="Reject"></input>-->
													<!--</form>-->
												<!--{% endif %}-->
											<!--</div>-->
										<!--</div>-->
									<!--</li>-->
							<!--{% else %}-->
								<!--{% if appointment.status != 'Pending'%}-->
									<!--<li>-->
										<!--<div class="col-md-3 col-sm-3 col-xs-3">-->
											<!--<div class="notify-img">-->
												<!--{% if appointment.lecID.profile.user_photo %}-->
													<!--<img src="{{ appointment.stuID.profile.user_photo.url }}" class="img-responsive" alt="">-->
												<!--{% else %}-->
													<!--<img src="{% static 'Profile/image/default.png' %}" class="img-responsive" alt="">-->
												<!--{% endif %}-->
											<!--</div>-->
										<!--</div>-->
										<!--<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="{% url 'Profile:profile' appointment.lecID.username %}">{{ appointment.lecID }}</a><a href="" class="rIcon"><i class=""></i></a>-->
											<!--<div>-->
												<!--<p>Date  : {{ appointment.date }}</p>-->
												<!--<p>Time  : {{ appointment.time }}</p>-->
												<!--<p>About : {{ appointment.reason }}</p>-->
												<!--<p>Status : {{ appointment.status }}</p>-->
												<!--{% if profile.user_type == 'Supervisor' %}-->
													<!--<form id="appointmentForm" method="post" enctype="multipart/form-data" action="">-->
														<!--{% csrf_token %}-->
														<!--<input class="hidden" name="appointment_id" value="{{ appointment.id }}">-->
														<!--<input type="submit" class="btn btn-primary pull-right" name="accept" value="Accept"></input>-->
														<!--<input type="submit" class="btn btn-danger pull-right" name="reject" value="Reject"></input>-->
													<!--</form>-->
												<!--{% endif %}-->
											<!--</div>-->
										<!--</div>-->
									<!--</li>-->
								<!--{% endif %}-->
							<!--{% endif %}-->
						<!--{% endfor %}-->
		            <!--</div>-->
		            <!--<div class="notify-drop-footer text-center">-->
		            	<!--<a href="{% url 'Appointment:booking' %}"><i class="fa fa-eye"></i> See All</a>-->
		            <!--</div>-->
		          <!--</ul>-->
		    </div>
		</div>

		<!--Item-->
		<div class= "collapse navbar-collapse" id="topNavBar">
				<ul class = "nav navbar-nav visible-xs">
						<li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}>
							<a href="{% url 'Profile:home' %}">
							<span class= "glyphicon glyphicon-user"></span>
							Profile</a>
						</li>
						<li {% if request.resolver_match.url_name == 'subject' %}class="active"{% endif %}>
							<a href="{% url 'subject:subject' %}">
							<span class= "glyphicon glyphicon-education"></span>
							Subject</a>
						</li>
						<li {% if request.resolver_match.url_name == 'file' %}class="active"{% endif %}>
							<a href="{% url 'file:file' %}">
							<span class= "glyphicon glyphicon-tasks"></span>
							File</a>
						</li>
						<li {% if request.resolver_match.url_name == 'account' %}class="active"{% endif %}>
							<a href="{% url 'Transaction:account' %}">
							<span class= "glyphicon glyphicon-stats"></span>
							Finance</a>
						</li>
				</ul>
			    <ul class="nav navbar-nav navbar-right">
		         <li class="dropdown hidden-xs">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class= "glyphicon glyphicon-bell" aria-hidden="true"></span> Notification <span class="badge badge-danger">{{ approved_app.count }}</span>
		          </a>
		          <ul class="dropdown-menu ">
		            <div class="notify-drop-title">
		            	<div class="row">
		                    <!--inside 1-->
		            		<div class="col-md-6 col-sm-6 col-xs-6">Notification</div>
		            		<div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title=""><i class="fa fa-dot-circle-o"></i></a></div>
		            	</div>
		            </div>
		            <!-- end notify title -->
		            <!-- notify content -->
		            <div class="drop-content">
						{% for appointment in approved_app %}
							{% if profile.user_type == 'Supervisor' %}
								{% if appointment.status == 'Pending' %}
									<li>
										<div class="col-md-3 col-sm-3 col-xs-3">
											<div class="notify-img">
												{% if appointment.stuID.profile.user_photo %}
													<img src="{{ appointment.stuID.profile.user_photo.url }}" class="img-responsive" alt="">
												{% else %}
													<img src="{% static 'Profile/image/default.png' %}" class="img-responsive" alt="">
												{% endif %}
											</div>
										</div>
										<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="{% url 'Profile:profile' appointment.stuID.username %}">{{ appointment.stuID }}</a><a href="" class="rIcon"><i class=""></i></a>
											<div>
												<p>Date  : {{ appointment.date }}</p>
												<p>Time  : {{ appointment.time }}</p>
												<p>About : {{ appointment.reason }}</p>

													<form id="appointmentForm" method="post" enctype="multipart/form-data" action="">
														{% csrf_token %}
														<input class="hidden" name="appointment_id" value="{{ appointment.id }}">
														<input type="submit" class="btn btn-primary pull-right" name="accept" value="Accept"></input>
														<input type="submit" class="btn btn-danger pull-right" name="reject" value="Reject"></input>
													</form>

											</div>
										</div>
									</li>
						          {% endif %}
							{% else %}
								{% if appointment.status != 'Pending'%}
									<li>
										<div class="col-md-3 col-sm-3 col-xs-3">
											<div class="notify-img">
												{% if appointment.lecID.profile.user_photo %}
													<img src="{{ appointment.stuID.profile.user_photo.url }}" class="img-responsive" alt="">
												{% else %}
													<img src="{% static 'Profile/image/default.png' %}" class="img-responsive" alt="">
												{% endif %}
											</div>
										</div>
										<div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="{% url 'Profile:profile' appointment.lecID.username %}">{{ appointment.lecID }}</a><a href="" class="rIcon"><i class=""></i></a>
											<div>
												<p>Date  : {{ appointment.date }}</p>
												<p>Time  : {{ appointment.time }}</p>
												<p>About : {{ appointment.reason }}</p>
												<p>Status : {{ appointment.status }}</p>
												{% if profile.user_type == 'Supervisor' %}
													<form id="appointmentForm" method="post" enctype="multipart/form-data" action="">
														{% csrf_token %}
														<input class="hidden" name="appointment_id" value="{{ appointment.id }}">
														<input type="submit" class="btn btn-primary pull-right" name="accept" value="Accept"></input>
														<input type="submit" class="btn btn-danger pull-right" name="reject" value="Reject"></input>
													</form>
											</div>
										</div>
									</li>
									{% endif %}
								{% endif %}
							{% endif %}
						{% endfor %}
		            </div>
		            <div class="notify-drop-footer text-center">
		            	<a href="{% url 'Appointment:booking' %}"><i class="fa fa-eye"></i> See All</a>
		            </div>
		          </ul>
		        </li>

				<li class="">
						<a href="{% url 'Profile:logout_user' %}" >
							<span class= "glyphicon glyphicon-off" aria-hidden="true"></span> Logout
						</a>
				</li>
			</ul>
			<form class="navbar-form navbar-right" role="search">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Search" name="q">
					<div class="input-group-btn">
						<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</nav>

{% block body %}
{% endblock %}

Code/pgms/Profile/templates/Profile/side_bar.html
{% extends 'Profile/navigation_bar.html' %}
{% block body %}
{% load staticfiles %}
<div class="container-fluid">
	<div class="row profile">
		<div class="col-md-4 col-sm-4 hidden-xs ">
			<div class="profile-sidebar col-md-3 col-sm-3" id="profile-sidebar">
				<!--profile picture-->
				<div class="profile-userpic">
					<center>
						<button type="button" class="btn btn-userpic">
							{% if profile.user_photo %}
								<img src="{{ profile.user_photo.url }}" class="img-responsive" alt="">
							{% else %}
								<img src="{% static 'Profile/image/default.png' %}" class="img-responsive" alt="">
							{% endif %}
						</button>
					</center>
				</div>
				<!--End of profile picture-->
				<!--sidebar user information -->
				<div class="profile-usertitle">
					<h4><strong>{{ profile.user.first_name }} {{ profile.user.last_name }}</strong></h4>
					<div>
						<strong>
							{% if profile.user_type == 'Student' %}
								{% if profile.stud_type == 'By Research' %}
									Research Student
								{% elif profile.stud_type == 'By Coursework'%}
									Coursework Student
								{% endif %}
							{% else %}
								{{ profile.user_type }}
							{% endif %}
						</strong>
					</div>
					<div>
						{{ profile.user.username }}
					</div>
				</div>
				<div class="profile-usermenu">
					<ul class = "nav navbar-fixed-left">
						<li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}>
							<a href="{% url 'Profile:home' %}">
							<span class= "glyphicon glyphicon-user"></span>
							Profile</a>
						</li>
						<li {% if request.resolver_match.url_name == 'subject' %}class="active"{% endif %}>
							<a href="{% url 'subject:subject' %}">
							<span class= "glyphicon glyphicon-education"></span>
							Subject</a>
						</li>
						<li {% if request.resolver_match.url_name == 'file' %}class="active"{% endif %}>
							<a href="{% url 'file:file' %}">
							<span class= "glyphicon glyphicon-tasks"></span>
							File</a>
						</li>
						<li  {% if request.resolver_match.url_name == 'account' %}class="active"{% endif %}>
							<a href="{% url 'Transaction:account' %}">
							<span class= "glyphicon glyphicon-stats"></span>
							Finance</a>
						</li>
					</ul>
				</div>
				<!--End Menu-->

			</div>
		</div>

		<div class="col-md-8 col-sm-8 col-xs-12">
			<div class="profile-content-head visible-xs">
				<!--profile picture-->
				<div class="profile-userpic">
					<center>
						<button type="button" class="btn btn-userpic">
							{% if profile.user_photo %}
								<img src="{{ profile.user_photo.url }}" class="img-responsive" alt="">
							{% else %}
								<img src="{% static 'Profile/image/default.png' %}" class="img-responsive" alt="">
							{% endif %}
						</button>
					</center>
				</div>
				<!--End of profile picture-->
				<!--sidebar user information -->
				<div class="profile-usertitle">
					<h4><strong>{{ profile.user.first_name }} {{ profile.user.last_name }}</strong></h4>
					<div>
						{% if profile.user_type == 'Student' %}
							{% if profile.stud_type == 'By Research' %}
								Research Student
							{% elif profile.stud_type == 'By Coursework'%}
								Coursework Student
							{% endif %}
						{% else %}
							{{ profile.user_type }}
						{% endif %}
					</div>
					<div>
						{{ profile.user.username }}
					</div>
				</div>
			</div>

			{% block content %}
			{% endblock %}

		</div>
	</div>

</div>

<script>
    $('.dropdown-menu').click(function(e) {
    e.stopPropagation();
    });
    $('#profile-sidebar').affix({
    	offset: {
        top: $('#scroll').height()
    }
	});
</script>

{% endblock %}